### PR TITLE
Add a landing page message

### PR DESCRIPTION
**Pull request by mkazhimHarry**
i have added the landing page message

### CODE REVIEW

**Review by mkazhimHermione — CHANGES_REQUESTED** [review]
Could you remove the 'Enjoy your stay' and make the string 'Welcome to the potify' red?

**Comment by mkazhimHarry** [comment]
Sure

**Review by mkazhimHermione — COMMENTED** [review]
Remove Enjoy your stay and make the Welcome to the potify red

**Review by mkazhimHermione — APPROVED** [review]
okay i like it. Well done Harry

**Pull request merged**
